version: '3.8'

services:
  db:
    platform: linux/amd64
    image: postgres:17
    container_name: postgres
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${AIV_DB_USER}
      POSTGRES_PASSWORD: ${AIV_DB_PASSWORD}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AIV_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    platform: linux/amd64
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      db:
        condition: service_healthy

  aiv:
    platform: linux/amd64
    container_name: aiv
    image: aivhub/aivlocal:6.4.0-2
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: >
      /bin/bash -c '
      rm /var/lib/aiv/drivers/flight-sql-jdbc-driver-10.0.0.jar &&
      exec /usr/bin/java --add-opens=java.base/java.nio=ALL-UNNAMED 
      --add-exports=java.base/sun.nio.ch=ALL-UNNAMED 
      --add-opens=java.base/sun.nio.ch=ALL-UNNAMED 
      --add-opens=java.base/sun.util.calendar=ALL-UNNAMED 
      -Dspring.config.location=/var/lib/aiv/repository/econfig/application.yml 
      -Dloader.path=/var/lib/aiv/drivers 
      -cp /var/lib/aiv/repository/econfig/:/var/lib/aiv/aiv.jar 
      org.springframework.boot.loader.launch.PropertiesLauncher'
    environment:
      aiv_port: 8080
      aiv_base: /var/lib/aiv
      aiv_db_url: jdbc:postgresql://db:5432/postgres
      aiv_db_user: ${AIV_DB_USER}
      aiv_db_password: ${AIV_DB_PASSWORD}
      security_db_url: jdbc:postgresql://db:5432/postgres?currentSchema=security
      security_db_user: ${AIV_DB_USER}
      security_db_password: ${AIV_DB_PASSWORD}
    volumes:
      - ./repository:/var/lib/aiv/repository:rw
      # - ./config/drivers:/var/lib/aiv/drivers
      # - ./logs:/opt/logs:rw
      # - ./dataloc:/usr/local/temp:rw
