version: '3.8'

services:
  db:
    platform: linux/amd64
    image: postgres:17
    container_name: postgres
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${AIV_DB_USER}
      POSTGRES_PASSWORD: ${AIV_DB_PASSWORD}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AIV_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    platform: linux/amd64
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      db:
        condition: service_healthy

  aiv: 
    platform: linux/amd64
    container_name: aiv
    image: jits023/aiv:6.3.6
    command: >
      /bin/bash -c '
      if [ ! -f "/opt/repository/econfig/application.yml" ]; then
        echo "Error: application.yml not found at /opt/repository/econfig/application.yml" && exit 1;
      fi &&
      if [ -d "/opt/config/drivers" ]; then
        echo "Drivers directory found at /opt/config/drivers";
      else
        echo "Warning: Drivers directory not found at /opt/config/drivers";
      fi &&
      echo "Starting AIV application..." &&
      java --add-opens=java.base/java.nio=ALL-UNNAMED 
      --add-exports=java.base/sun.nio.ch=ALL-UNNAMED 
      --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/sun.util.calendar=ALL-UNNAMED 
      -Dspring.config.location=/opt/repository/econfig/application.yml 
      -Dloader.path=/opt/config/drivers 
      -cp /opt/repository/econfig/:run.jar 
      org.springframework.boot.loader.launch.PropertiesLauncher'
    ports: 
      - "8080:8080"
    depends_on:
      - db
    environment:
      aiv_port: 8080
      aiv_base: /opt
      aiv_db_url: jdbc:postgresql://db:5432/postgres
      aiv_db_user: ${AIV_DB_USER}
      aiv_db_password: ${AIV_DB_PASSWORD}
      security_db_url: jdbc:postgresql://db:5432/postgres?currentSchema=security
      security_db_user: ${AIV_DB_USER}
      security_db_password: ${AIV_DB_PASSWORD}
    volumes:
      - ./config:/opt/config:rw
      - ./repository:/opt/repository:rw
      - ./logs:/opt/logs:rw
      - ./dataloc:/usr/local/temp:rw

  aiv-ai: 
    container_name: aiv-ai
    image: jits023/aiv-ai:6.3.0
    ports: 
      - "8001:8001"
    environment:
      - AIV_JUPYTER=aiv-jupyter
      - AIV_TOKEN=aivhub
    volumes:
      - ./ai/dataloc:/usr/local/temp:rw
      - ./ai/data:/app/data
      - ./ai/scriptfiles:/app/scriptfiles
    restart: always
