version: '3.8'

services:
  db:
    platform: linux/amd64
    image: postgres:17
    container_name: postgres
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${AIV_DB_USER}
      POSTGRES_PASSWORD: ${AIV_DB_PASSWORD}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AIV_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    platform: linux/amd64
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      db:
        condition: service_healthy

  aiv:
    platform: linux/amd64
    container_name: aiv
    image: aivhub/aivlocal:6.0.2
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      aiv_port: 8080
      aiv_base: /opt
      aiv_db_url: jdbc:postgresql://db:5432/postgres
      aiv_db_user: ${AIV_DB_USER}
      aiv_db_password: ${AIV_DB_PASSWORD}
      security_db_url: jdbc:postgresql://db:5432/postgres?currentSchema=security
      security_db_user: ${AIV_DB_USER}
      security_db_password: ${AIV_DB_PASSWORD}
    volumes:
      - ./repository:/opt/repository:rw
      - ./config/drivers:/opt/config/drivers
      # - ./logs:/opt/logs:rw
      # - ./dataloc:/usr/local/temp:rw
