name: Build Debian Package

on:
  push:
    tags: [ 'debian/*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get run.jar from Docker image
      run: |
        docker pull jits023/aiv:6.3.4
        docker create --name aiv_container jits023/aiv:6.3.4
        docker cp aiv_container:/opt/run.jar aiv.jar
        docker rm -f aiv_container

    - name: Build debian package
      run: bash aiv-build-deb.sh

    - name: Rename package to debian 11,12 format and tag versionn if available
      if: startsWith(github.ref, 'refs/tags/debian/')
      env:
        TAG: ${{ github.ref_name }}
      run: |
        # extract version from tag
        VERSION=$(echo $TAG | sed 's/debian\///')
        # rename package
        mv aiv-build.deb aiv-${VERSION}-deb11a12.deb
        echo "Renamed package to aiv-${VERSION}-deb11a12.deb"


    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aiv-build-package
        path: aiv-build.deb

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          aiv-*.deb
